### ISSUE TITLE
Support more compute types for google_compute_region_commitment

### ISSUE THREAD

**Issue by YpNo** [hashicorp/terraform-provider-google#14560]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Commitment is applied on different compute types. Most of the general types is missing. We have to add the following types:
* GENERAL_PURPOSE_N1
* GENERAL_PURPOSE_N2
* GENERAL_PURPOSE_N2D
* GENERAL_PURPOSE_E2
* GENERAL_PURPOSE_T2D
* GENERAL_PURPOSE_C3
* COMPUTE_OPTIMIZED_C2
* COMPUTE_OPTIMIZED_C2D
* GRAPHICS_OPTIMIZED_G2

### Affected Resource(s)

* google_compute_region_commitment

### Potential Terraform Configuration

```tf
resource "google_compute_region_commitment" "foobar" {
  name = "my-full-commitment"
  description = "some description"
  plan = "TWELVE_MONTH"
  type = "GENERAL_PURPOSE_N2"
  category = "MACHINE"
  auto_renew = true
  resources {
      type = "VCPU"
      amount = "4"
  }
  resources {
      type = "MEMORY"
      amount = "9"
  }
}
```

**Comment by YpNo** [comment]
Waiting for the new provider release to validate

**Comment by rileykarson** [comment]
Resolved in https://github.com/GoogleCloudPlatform/magic-modules/pull/7915, we typically close issues @ merge time.

**Comment by YpNo** [comment]
Hi @rileykarson,

It seams that the new version of provider doesn't include my update. Maybe I've missed something.
The documentation is not up-to-date and when I've tried my terraform code with the latest version I still have an error about "expected type".

Regards.

**Comment by rileykarson** [comment]
That's expected, it should be in `4.66.0`. I closed this because we typically close issues when merging, not releasing.
